blog/urls.py
from django.urls import path
from .views import HomeView, BlogPostView, Success, Posts, SinglePost

app_name = 'blog'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('new_post/',BlogPostView.as_view(), name='blog_post'),
    path('success/', Success.as_view(), name='success'),
    path('posts/', Posts.as_view(), name='posts'),
    path("posts/<int:pk>",SinglePost.as_view(), name='post_detail_view')
]

website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
    path("", RedirectView.as_view(url='blog/'))
    
]

blog/models.py
from django.db import models

# Create your models here.


class BlogPost(models.Model):
    title = models.CharField(max_length=250)
    post = models.TextField()

    def __str__(self):
        return f"{self.title}, {self.post}"

blog/forms.py
from django import forms
from .models import BlogPost
from django.forms import ModelForm, TextInput, Textarea

class BlogPostForm(ModelForm):  
    class Meta:
        model = BlogPost
        fields = ['title', 'post']
        widgets = {
            'title': TextInput(attrs={
                'class':'form-control',
                'style': 'max-width: 300px;',
                'placeholder':'Title'
            }),
            'post': Textarea(attrs={
                'class':'form-control',
                'placeholder':'Write your post here'
    
            })
        }


    # title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Title', 'style': 'width: 300px;', 'class': 'form-control'}))
    # post = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'New Post','class':'form-control'}))
    
    # title = forms.CharField(label="Title", max_length=30)
    # post = forms.CharField(label="Please write your post here", widget=forms.Textarea)

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, ListView, DetailView
from blog.forms import BlogPostForm
from blog.models import BlogPost

# Create your views here.

class HomeView(TemplateView):
    template_name = 'blog/home.html'



class BlogPostView(FormView):
    form_class = BlogPostForm
    template_name = 'blog/new_post.html'
    success_url = reverse_lazy('blog:posts')
    def form_valid(self, form):
        print(form.cleaned_data)
        form.save()
        return super().form_valid(form)

class Success(TemplateView):
    template_name = 'blog/success.html'

class Posts(ListView):
    model = BlogPost
    context_object_name = 'blog_posts'

class SinglePost(DetailView):
    model = BlogPost

blog/templates/blog/BlogPost_detail.html
{% extends 'base.html' %} {% block content %}

<h2>{{blogpost}}</h2>

{% endblock content %}

blog/templates/blog/BlogPost_form.html
{% extends 'base.html' %} {% block content %}

<h1>NEW BLOG POST</h1>

<form action="" method="POST">
  {% csrf_token %}
  <div class="form-group">{{form.title}}</div>
  <div class="form-group">{{form.post}}</div>
  <div class="form-group">
    <input
      class="form-control form-control-log"
      type="submit"
      name=""
      id=""
      value="Submit"
    />
  </div>
</form>

{% endblock content %}

blog/templates/blog/BlogPost_list.html
{% extends 'base.html' %} {% block content %}
<h1>BLOG POSTS LIST</h1>

<ul>
  {% for post in blog_posts %}
  <li>
    <a href="/blog/posts/{{post.id}}">{{post.title}}</a>
    <p>{{post.post}}</p>
  </li>
  {% endfor %}
</ul>
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %} {% block content %}
<h1>HOME PAGE</h1>

<a href="{% url 'blog:posts'%}">Posts</a>

{% endblock content %}

blog/templates/blog/new_post.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <h1>New Entry</h1>

  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">{{form.title}}</div>
    <div class="form-group">{{form.post}}</div>
    <div class="form-group">
      <input type="submit" name="" id="" value="Submit" />
    </div>
  </form>
</div>

{% endblock content %}

blog/templates/blog/posts.html
{% comment %} {% extends 'base.html' %} {% block content %}
<h1>BLOG POSTS</h1>

<ul>
  {% for post in blog_posts %}
  <li>
    <a href="/blog/BlogPost_detail/{{blog_post.id}}">{{blog_posts.title}}</a>
    <p>{{blog_posts.post}}</p>
  </li>
  {% endfor %}
</ul>
{% endblock content %} {% endcomment %}

blog/templates/blog/success.html
{% extends 'base.html' %} {% block content %}
<h1>POST SUCCESSFUL</h1>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'blog/blog-styles.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </head>
  <header>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Daily Progress Journal</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'blog:posts'%}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:posts'%}">Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blog:blog_post'%}">New Post</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>

    {% block content %} {% endblock content %}

    <script src="" async defer></script>
  </body>
  <footer></footer
</html>